name: Packer Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Packer Build
    runs-on: ubuntu-latest

    # if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_AccessKey }}
          aws-secret-access-key: ${{ secrets.AWS_SecretAccessKey }}
          aws-region: us-east-1
        continue-on-error: false   

      - name: Initialize and Validate Packer Template
        run: |
          cd ./packer/

          packer init jenkins-ami.pkr.hcl
          packer validate jenkins-ami.pkr.hcl

      - name: Format Packer Template
        run: |
          cd ./packer/
          packer fmt jenkins-ami.pkr.hcl

      - name: Build Image with Packer
        run: |
          cd ./packer/
          packer build -var "GH_USERNAME=${{ secrets.GH_USERNAME }}" -var "GH_CREDS=${{ secrets.GH_CREDS }}" -var "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" -var "DOCKERHUB_CREDS=${{ secrets.DOCKERHUB_CREDS }}" jenkins-ami.pkr.hcl 

      